#!/usr/bin/env python3

import os
import sys
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from app import app, db
from models import Department, User

def create_departments_table():
    """Create departments table and add some sample departments"""

    with app.app_context():
        # Create the departments table
        try:
            with db.engine.connect() as connection:
                connection.execute(db.text("""
                    CREATE TABLE departments (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR2(100) NOT NULL,
                        description CLOB,
                        manager_id NUMBER,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        is_active NUMBER(1) DEFAULT 1,
                        CONSTRAINT fk_department_manager FOREIGN KEY (manager_id) REFERENCES users(id)
                    )
                """))
                connection.commit()
            print("✅ Departments table created successfully")
        except Exception as e:
            if "name is already used by an existing object" in str(e):
                print("⚠️  Departments table already exists")
            else:
                print(f"❌ Error creating departments table: {e}")
                return False

        # Add sample departments
        try:
            sample_departments = [
                {
                    'name': 'Human Resources',
                    'description': 'Manages employee relations, recruitment, and HR policies'
                },
                {
                    'name': 'Information Technology',
                    'description': 'Manages company technology infrastructure and software development'
                },
                {
                    'name': 'Finance',
                    'description': 'Handles financial planning, accounting, and budget management'
                },
                {
                    'name': 'Marketing',
                    'description': 'Manages marketing campaigns, brand awareness, and customer outreach'
                },
                {
                    'name': 'Operations',
                    'description': 'Oversees daily business operations and process optimization'
                }
            ]

            # Check if departments already exist
            existing_departments = Department.query.count()
            if existing_departments == 0:
                for dept_data in sample_departments:
                    department = Department(
                        name=dept_data['name'],
                        description=dept_data['description'],
                        is_active=True
                    )
                    db.session.add(department)

                db.session.commit()
                print(f"✅ Added {len(sample_departments)} sample departments")
            else:
                print(f"⚠️  {existing_departments} departments already exist")

        except Exception as e:
            print(f"❌ Error adding sample departments: {e}")
            db.session.rollback()
            return False

        return True

if __name__ == "__main__":
    success = create_departments_table()
    if success:
        print("🎉 Department table setup completed successfully!")
    else:
        print("💥 Department table setup failed!")